// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4cKrIZ8ySIqFYLm1qdpuUR62_hI0sFPo',
    appId: '1:679085338205:web:9528892027225ce85827b4',
    messagingSenderId: '679085338205',
    projectId: 'bolt-19409',
    authDomain: 'bolt-19409.firebaseapp.com',
    storageBucket: 'bolt-19409.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt4YqC7QFS9cJBNwFnrY38Ts0M2la0uak',
    appId: '1:679085338205:android:a40b514bb52120405827b4',
    messagingSenderId: '679085338205',
    projectId: 'bolt-19409',
    storageBucket: 'bolt-19409.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3idJohBrmdVDYW95Qrz0BYznKLdCcAVI',
    appId: '1:679085338205:ios:20050372aec1b2835827b4',
    messagingSenderId: '679085338205',
    projectId: 'bolt-19409',
    storageBucket: 'bolt-19409.appspot.com',
    iosBundleId: 'com.example.bolt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3idJohBrmdVDYW95Qrz0BYznKLdCcAVI',
    appId: '1:679085338205:ios:c1003f116bd216f75827b4',
    messagingSenderId: '679085338205',
    projectId: 'bolt-19409',
    storageBucket: 'bolt-19409.appspot.com',
    iosBundleId: 'com.example.bolt.RunnerTests',
  );
}
